---
title: "R Notebook"
---

```{r}
library(terra)
library(dplyr)
library(tidyr)
library(purrr)
grid <- rast("../../grid/outputs/grid_250m.tif")
```

# Calculate total fishing hours each year per grid cell
# Warning: this will take a while to run
```{r}
for(i in 2019:2020){
  yr <- i
  l <- list.files(path = paste0("inputs/gfw/fleet-daily-csvs-100-v2-", yr), pattern = "*.csv", full.names = TRUE)
  
  dat <- l %>% map_dfr(read.csv)
  dat$latlong <- paste0(dat$cell_ll_lat, ", ", dat$cell_ll_lon)
  
  dat_sum <- dat %>% 
    group_by(latlong) %>% 
    summarise(fishing_hours = sum(fishing_hours),
              lat = mean(cell_ll_lat),
              long = mean(cell_ll_lon))
  
  dat_sum <- filter(dat_sum, lat > 52 & lat < 68 & long > 6 & long < 35)
  dat_sum <- select(dat_sum, lat, long, fishing_hours)
  write.csv(dat_sum, 
            paste0("inputs/gfw_sum/fleet-daily-csvs-100-v2-", yr, "_sum.csv"),
            row.names = FALSE)
  cat("\nYear ", yr, "done")
}
```

# More robust and less memory needed
```{r}
for(j in 2012:2012){
  yr <- j
  l <- list.files(path = paste0("inputs/gfw/fleet-daily-csvs-100-v2-", yr), pattern = "*.csv", full.names = TRUE)
  
  for(i in 1:length(l)){
  #for(i in 1:1){
    if(i == 1){dat <- read.csv(l[i])} else {
    
    dat <- filter(dat, cell_ll_lat > 52 & cell_ll_lat < 68 & cell_ll_lon > 6 & cell_ll_lon < 35)
    dat <- select(dat, cell_ll_lat, cell_ll_lon, fishing_hours)  
    temp <- read.csv(l[i])
    temp <- filter(temp, cell_ll_lat > 52 & cell_ll_lat < 68 & cell_ll_lon > 6 & cell_ll_lon < 35)
    temp <- select(temp, cell_ll_lat, cell_ll_lon, fishing_hours)
    dat <- rbind(dat, temp)
    dat$latlong <- paste0(dat$cell_ll_lat, ", ", dat$cell_ll_lon)
    
    dat <- dat %>% 
      group_by(latlong) %>% 
      summarise(fishing_hours = sum(fishing_hours),
                cell_ll_lat = mean(cell_ll_lat),
                cell_ll_lon = mean(cell_ll_lon)) %>%
      ungroup()
  
    }
    cat("\nIteration ", i, "done")
  }
  
  dat <- select(dat, cell_ll_lat, cell_ll_lon, fishing_hours)
  colnames(dat) <- c("lat", "long", "fishing_hours")
  write.csv(dat,
            paste0("inputs/gfw_sum/_archive/fleet-daily-csvs-100-v2-", yr, "_sum.csv"), 
            row.names = FALSE)
  cat("\nIteration ", j, "done")

}
```

# Summarise fishing data
## There appears to be some error of recording fishing when
## boats are likely anchored. We can optinally remove these cells
```{r}
rem_errors <- function(x){
  x$fishing_hours[which(x$lat == 56.92 & x$long == 12.35)] <- 0
  x$fishing_hours[which(x$lat == 60.48 & x$long == 21.48)] <- 0
  x$fishing_hours[which(x$lat == 57.71 & x$long == 10.50)] <- 0
  x$fishing_hours[which(x$lat == 57.49 & x$long == 10.58)] <- 0
  x$fishing_hours[which(x$lat == 60.18 & x$long == 22.06)] <- 0
  x$fishing_hours[which(x$lat == 57.49 & x$long == 10.50)] <- 0
  return(x)
}

for(i in 2012:2020){
  dat <- read.csv(paste0("inputs/gfw_sum/fleet-daily-csvs-100-v2-", i, "_sum.csv"))
  #dat <- vect(dat, geom = c("long", "lat"), crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
  dat <- select(dat, long, lat, fishing_hours)
  dat <- rem_errors(dat)
  temp <- rast(dat, type = "xyz", crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
  temp <- project(temp, grid, method = "near")
  temp <- temp * grid
  names(temp) <- paste0(i)
  if(i == 2012){gfw <- temp} else {
    gfw <- c(gfw, temp)
  }
}

plot(gfw)
```
# Mean fishing hours per year from 2012 to 2020
```{r}
gfw_mean <- app(gfw, fun = mean, na.rm = TRUE)
gfw_mean[is.na(gfw_mean)] <- 0
gfw_mean[is.na(grid)] <- NA

writeRaster(gfw_mean, "outputs/gfw_mean_250m.tif", overwrite = TRUE,
            datatype = "INT2S", gdal=c("COMPRESS=ZSTD", "PREDICTOR=2"))
plot(gfw_mean)
```

# Fishing hours quantiles
```{r}
gfw_mean <- app(gfw, fun = mean, na.rm = TRUE)
gfw_mean[is.na(gfw_mean)] <- 0
gfw_mean[is.na(grid)] <- NA

v <- values(gfw_mean, na.rm = TRUE)
v <- v[v > 0]
p <- quantile(v, probs = seq(0.1, 0.9, 0.1), na.rm = TRUE)

gfw_q <- gfw_mean
gfw_q[gfw_mean < p[1]] <- 1
gfw_q[gfw_mean >= p[1] & gfw_mean < p[2]] <- 2
gfw_q[gfw_mean >= p[2] & gfw_mean < p[3]] <- 3
gfw_q[gfw_mean >= p[3] & gfw_mean < p[4]] <- 4
gfw_q[gfw_mean >= p[4] & gfw_mean < p[5]] <- 5
gfw_q[gfw_mean >= p[5] & gfw_mean < p[6]] <- 6
gfw_q[gfw_mean >= p[6] & gfw_mean < p[7]] <- 7
gfw_q[gfw_mean >= p[7] & gfw_mean < p[8]] <- 8
gfw_q[gfw_mean >= p[8] & gfw_mean < p[9]] <- 9
gfw_q[gfw_mean >= p[9]] <- 10

writeRaster(gfw_q, "outputs/gfw_quantiles_250m.tif", overwrite = TRUE,
            datatype = "INT2S", gdal=c("COMPRESS=ZSTD", "PREDICTOR=2"))

plot(gfw_q)
```
