---
title: "R Notebook"
---

```{r}
library(terra)
library(rasterVis)
library(RColorBrewer)
library(dplyr)
grid <- rast("inputs/grid/grid_250m.tif")
```


# Median PA
# "Abra alba", "Bathyporeia pilosa", "Macoma balthica", "Marenzelleria neglecta"
```{r}
spec <- "Marenzelleria neglecta"
spec_ <- gsub(" ", "_", spec)

## Import observations
#mod_dir <- paste0(sdir, "/", gsub(" ", "_", spec), "_model.sdm")
obs_dir <- paste0("../input_data/observations/", spec_, "_observations.csv")
obs <- read.csv(obs_dir)
obs <- filter(obs, count == 1)
obs <- select(obs, count, long, lat)
obs <- vect(obs, geom = c("long", "lat"), crs="+proj=longlat +datum=WGS84")
obs <- project(obs, crs(grid))

r_fp <- paste0("outputs/local/run2/", spec_,  "/ensemble_projections/", spec_, "_EMwmeanByROC_allData_RUN", c(1,2,3), "_mergedAlgo.tif")
r <- rast(r_fp)*grid

r_temp <- app(r, fun = mean)
names(r_temp) <- paste0(spec_, "_probability")
raster_res <- res(r)
raster_dims <- dim(r)
#fp <- tools::file_path_sans_ext(basename(r_list[i]))

png(paste0("biomod_maps/", spec_, "_probs_ROC_mean.png"), width = raster_dims[2], height = raster_dims[1], units = "px", res = 300)
clrs <- colorRampPalette(colors = rev(c('#d73027','#f46d43','#fdae61','#fee08b','#ffffbf','#d9ef8b','#a6d96a','#66bd63','#1a9850')))(100)
#plot(r_temp, col = spectral_colors, axes = FALSE, legend = FALSE, box = TRUE, maxcell = 1e6)
plot(r_temp, col = clrs, axes = FALSE, legend = FALSE, box = TRUE, maxcell = 1e7)
plot(obs, add = TRUE)
#box(col = "black", lwd = 2)
dev.off()
```

# Mean probability
# "Abra alba", "Bathyporeia pilosa", "Macoma balthica", "Marenzelleria neglecta"
```{r}
spec <- "Abra alba"
spec_ <- gsub(" ", "_", spec)

## Import observations
#mod_dir <- paste0(sdir, "/", gsub(" ", "_", spec), "_model.sdm")
obs_dir <- paste0("../input_data/observations/", spec_, "_observations.csv")
obs <- read.csv(obs_dir)
obs <- filter(obs, count == 1)
obs <- select(obs, count, long, lat)
obs <- vect(obs, geom = c("long", "lat"), crs="+proj=longlat +datum=WGS84")
obs <- project(obs, crs(grid))

r_fp <- paste0("outputs/local/run2/", spec_,  "/ensemble_projections/ensemble_TSSbin.tif")
r <- rast(r_fp)*grid

r_temp <- app(r, fun = median)
names(r_temp) <- paste0(spec_, "_PA")
raster_res <- res(r)
raster_dims <- dim(r)
#fp <- tools::file_path_sans_ext(basename(r_list[i]))

png(paste0("biomod_maps/", spec_, "_PA_TSS_median.png"), width = raster_dims[2], height = raster_dims[1], units = "px", res = 300)
clrs <- colorRampPalette(colors = c("grey70", "#1a9850"))(6)
#plot(r_temp, col = spectral_colors, axes = FALSE, legend = FALSE, box = TRUE, maxcell = 1e6)
plot(r_temp, col = clrs, axes = FALSE, legend = FALSE, box = TRUE, maxcell = 1e7)
plot(obs, add = TRUE)
#box(col = "black", lwd = 2)
dev.off()
```


*********************************************************************************

```{r}
r_list <- c("outputs/sprattus/run3/Abra_alba/ensemble_projections/Abra_alba_EMwmeanByROC_allData_RUN1_mergedAlgo.tif",
            "outputs/sprattus/run3/Abra_alba/ensemble_projections/Abra_alba_EMwmeanByROC_allData_RUN2_mergedAlgo.tif",
            "outputs/sprattus/run3/Abra_alba/ensemble_projections/Abra_alba_EMwmeanByROC_allData_RUN3_mergedAlgo.tif",
            "outputs/sprattus/run3/Bathyporeia_pilosa/ensemble_projections/Bathyporeia_pilosa_EMwmeanByROC_allData_RUN1_mergedAlgo.tif",
            "outputs/sprattus/run3/Bathyporeia_pilosa/ensemble_projections/Bathyporeia_pilosa_EMwmeanByROC_allData_RUN2_mergedAlgo.tif",
            "outputs/sprattus/run3/Bathyporeia_pilosa/ensemble_projections/Bathyporeia_pilosa_EMwmeanByROC_allData_RUN3_mergedAlgo.tif",
            "outputs/sprattus/run3/Macoma_balthica/ensemble_projections/Macoma_balthica_EMwmeanByROC_allData_RUN1_mergedAlgo.tif",
            "outputs/sprattus/run3/Macoma_balthica/ensemble_projections/Macoma_balthica_EMwmeanByROC_allData_RUN2_mergedAlgo.tif",
            "outputs/sprattus/run3/Macoma_balthica/ensemble_projections/Macoma_balthica_EMwmeanByROC_allData_RUN3_mergedAlgo.tif")

for(i in 1:length(r_list)){
  r <- rast(r_list[i])
  
  fp <- tools::file_path_sans_ext(basename(r_list[i]))
  
  png(paste0("biomod_maps/", fp, ".png"), width = 2481, height = 3507, units = "px", res = 300)
  spectral_colors <- rev(brewer.pal(11, "Spectral"))
  plot(r, col = spectral_colors, axes = FALSE, legend = FALSE, box = TRUE)
  #box(col = "black", lwd = 2)
  dev.off()
}
```


```{r}
r_list <- c("outputs/local/run2/Abra_alba/ensemble_projections/Abra_alba_EMwmeanByROC_allData_RUN1_mergedAlgo.tif",
            "outputs/local/run2/Abra_alba/ensemble_projections/Abra_alba_EMwmeanByROC_allData_RUN2_mergedAlgo.tif",
            "outputs/local/run2/Abra_alba/ensemble_projections/Abra_alba_EMwmeanByROC_allData_RUN3_mergedAlgo.tif",
            "outputs/local/run2/Bathyporeia_pilosa/ensemble_projections/Bathyporeia_pilosa_EMwmeanByROC_allData_RUN1_mergedAlgo.tif",
            "outputs/local/run2/Bathyporeia_pilosa/ensemble_projections/Bathyporeia_pilosa_EMwmeanByROC_allData_RUN2_mergedAlgo.tif",
            "outputs/local/run2/Bathyporeia_pilosa/ensemble_projections/Bathyporeia_pilosa_EMwmeanByROC_allData_RUN3_mergedAlgo.tif",
            "outputs/local/run2/Macoma_balthica/ensemble_projections/Macoma_balthica_EMwmeanByROC_allData_RUN1_mergedAlgo.tif",
            "outputs/local/run2/Macoma_balthica/ensemble_projections/Macoma_balthica_EMwmeanByROC_allData_RUN2_mergedAlgo.tif",
            "outputs/local/run2/Macoma_balthica/ensemble_projections/Macoma_balthica_EMwmeanByROC_allData_RUN3_mergedAlgo.tif")

for(i in 1:length(r_list)){
  r <- rast(r_list[i])
  raster_res <- res(r)
  raster_dims <- dim(r)
  
  fp <- tools::file_path_sans_ext(basename(r_list[i]))
  
  png(paste0("biomod_maps/", fp, ".png"), width = raster_dims[2], height = raster_dims[1], units = "px", res = 300)
  spectral_colors <- rev(brewer.pal(11, "Spectral"))
  plot(r, col = spectral_colors, axes = FALSE, legend = FALSE, box = TRUE, maxcell = 1e7)
  #box(col = "black", lwd = 2)
  dev.off()
}
```


```{r}
spec <- "Abra alba"
spec_ <- gsub(" ", "_", spec)

## Import observations
#mod_dir <- paste0(sdir, "/", gsub(" ", "_", spec), "_model.sdm")
obs_dir <- paste0("../input_data/observations/", spec_, "_observations.csv")
obs <- read.csv(obs_dir)
obs <- filter(obs, count == 1)
obs <- select(obs, count, long, lat)
obs <- vect(obs, geom = c("long", "lat"), crs="+proj=longlat +datum=WGS84")
obs <- project(obs, crs(grid))

r_fp <- "outputs/local/run2/Abra_alba/ensemble_projections/proj_misc_temp991472492_ensemble_TSSbin.tif"
r <- rast(r_fp)*grid

i <- 1
r_temp <- r[[i]]
names(r_temp) <- paste0(spec_, "_PA_RUN", i)
raster_res <- res(r)
raster_dims <- dim(r)
#fp <- tools::file_path_sans_ext(basename(r_list[i]))

png(paste0("biomod_maps/", spec_, "_PA_RUN", i, ".png"), width = raster_dims[2], height = raster_dims[1], units = "px", res = 300)
clrs <- colorRampPalette(colors = c("grey70", "#1a9850"))(6)
#plot(r_temp, col = spectral_colors, axes = FALSE, legend = FALSE, box = TRUE, maxcell = 1e6)
plot(r_temp, col = clrs, axes = FALSE, legend = FALSE, box = TRUE, maxcell = 1e7)
plot(obs, add = TRUE)
#box(col = "black", lwd = 2)
dev.off()
```