---
title: "R Notebook"
---

```{r}
library(CopernicusMarine)
library(terra)
grid <- rast("../../grid/outputs/grid_250m.tif")
if(!dir.exists("inputs/temp")){dir.create("inputs/temp", recursive = TRUE)}
if(!dir.exists("outputs")){dir.create("outputs")}
source("../_functions/resint.R") # Script for resampling
```

# Pull data from Copernicus
```{r}
file_tibble <- cms_list_stac_files("BALTICSEA_MULTIYEAR_PHY_003_011", "cmems_mod_bal_phy_my_P1M-m")
```

# Examine table to determine which years/months to download
```{r}
file_tibble <- file_tibble[253:348,]
cms_download_stac(file_tibble, destination = "inputs/temp")
```

# Show available variables
```{r}
l <- list.files("inputs/temp", full.names = TRUE)
r <- rast(l[1])
names(r)
```

# Summer bottom temperature means
```{r}
l <- list.files("inputs/temp", full.names = TRUE)
l <- l[grepl(".*(05|06|07)\\.nc$", l)] # Filter June, July, August

for(i in 1:length(l)){
  if(i == 1){r <- rast(l[i])[["bottomT"]]} else {
    r <- c(r, rast(l[i])[["bottomT"]])
  }
}

temp <- app(r, fun = mean)
temp <- project(temp, grid, method = "near")
temp <- temp*grid
writeRaster(temp, "outputs/summer_bottomT_mean_250m.tif", overwrite = TRUE, 
            datatype = "FLT4S", gdal=c("COMPRESS=ZSTD", "PREDICTOR=2"))
```

## Resample to higher resolution
```{r}
temp <- app(r, fun = mean)
temp_res <- resint(temp, grid, nit = 200, win_size = 3, method = "cubic")
writeRaster(temp_res, "outputs/summer_bottomT_mean_resample_250m.tif", overwrite = TRUE, 
            datatype = "FLT4S", gdal=c("COMPRESS=ZSTD", "PREDICTOR=2"))
```

# Winter bottom temperature means
```{r}
l <- list.files("inputs/temp", full.names = TRUE)
l <- l[grepl(".*(12|01|02)\\.nc$", l)] # Filter December, January, February

for(i in 1:length(l)){
  if(i == 1){r <- rast(l[i])[["bottomT"]]} else {
    r <- c(r, rast(l[i])[["bottomT"]])
  }
}

temp <- app(r, fun = mean)
temp <- project(temp, grid, method = "near")
temp <- temp*grid
writeRaster(temp, "outputs/winter_bottomT_mean_250m.tif", overwrite = TRUE, 
            datatype = "FLT4S", gdal=c("COMPRESS=ZSTD", "PREDICTOR=2"))
```

## Resample to higher resolution
```{r}
temp <- app(r, fun = mean)
temp_res <- resint(temp, grid, nit = 200, win_size = 3, method = "cubic")
writeRaster(temp_res, "outputs/winter_bottomT_mean_resample_250m.tif", overwrite = TRUE, 
            datatype = "FLT4S", gdal=c("COMPRESS=ZSTD", "PREDICTOR=2"))
```

# Year-round bottom temperature means
```{r}
l <- list.files("inputs/temp", full.names = TRUE)
#l <- l[grepl(".*(12|01|02)\\.nc$", l)] # Filter December, January, February

for(i in 1:length(l)){
  if(i == 1){r <- rast(l[i])[["bottomT"]]} else {
    r <- c(r, rast(l[i])[["bottomT"]])
  }
}

temp <- app(r, fun = mean)
temp <- project(temp, grid, method = "near")
temp <- temp*grid
writeRaster(temp, "outputs/year_round_bottomT_mean_250m.tif", overwrite = TRUE, 
            datatype = "FLT4S", gdal=c("COMPRESS=ZSTD", "PREDICTOR=2"))
```

## Resample to higher resolution
```{r}
temp <- app(r, fun = mean)
temp_res <- resint(temp, grid, nit = 200, win_size = 3, method = "cubic")
writeRaster(temp_res, "outputs/year_round_bottomT_mean_resample_250m.tif", overwrite = TRUE, 
            datatype = "FLT4S", gdal=c("COMPRESS=ZSTD", "PREDICTOR=2"))
```

# Remove netCDF files from disk
```{r}
l <- list.files("inputs/temp", full.names = TRUE)
file.remove(l) 
```

