---
title: "R Notebook"
---

```{r, include = FALSE}
library(dplyr)
library(sdm)
library(terra)
library(scales)
library(lubridate)
library(leaflet)
library(vctrs)

grid <- rast("../../../grid/outputs/grid_250m.tif")
```

# Import and filter observation data
```{r}
df <- read.csv("ICES_benthic_species_zoobenthos_23082024.csv", sep = "|")
df$date <- ymd_hms(df$date)

# Use only counts of individuals
df <- filter(df, q_unit == "individuals")

df <- df %>%
  group_by(date, start_lat, start_long) %>%
  reframe(scien_name = c(scien_name, "_absence"),
          origin_id = c(origin_id, NA),
          station_id = c(station_id, NA),
          sample_id = c(sample_id, NA),
          quantity = c(quantity, 0),
          q_type = c(q_type, NA),
          q_unit = c(q_unit, "individuals")
          )

df <- df %>%
  group_by(date, start_lat, start_long) %>%
  mutate(group_id = cur_group_id())

df <- relocate(df, group_id)

spec_list <- names(summary(as.factor(df$scien_name)))
spec_list <- spec_list[-1]
spec_list <- spec_list[-99]
```


```{r}
for(i in 1:length(spec_list)){
  df <- read.csv("ICES_benthic_species_zoobenthos_23082024.csv", sep = "|")
  df$date <- ymd_hms(df$date)
  
  # Use only counts of individuals
  df <- filter(df, q_unit == "individuals")
  
  df <- df %>%
    group_by(date, start_lat, start_long) %>%
    reframe(scien_name = c(scien_name, "_absence"),
            origin_id = c(origin_id, NA),
            station_id = c(station_id, NA),
            sample_id = c(sample_id, NA),
            quantity = c(quantity, 0),
            q_type = c(q_type, NA),
            q_unit = c(q_unit, "individuals")
            )
  
  df <- df %>%
    group_by(date, start_lat, start_long) %>%
    mutate(group_id = cur_group_id())
  
  df <- relocate(df, group_id)
  
  spec <- spec_list[i]
  #sdir <- paste0("outputs/", gsub(" ", "_", spec))
  #mod_dir <- paste0(sdir, "/", gsub(" ", "_", spec), "_model.sdm")
  #if(!dir.exists(sdir)){dir.create(sdir)}
  df <- filter(df, scien_name == spec | scien_name == "_absence") # Make sure to include absence records
  
  # Set absences to species name, absence = when count is 0
  df$scien_name[df$scien_name == "_absence"] <- spec
  
  # Calculate species count in each sample
  obs <- df %>%
    group_by(group_id, scien_name) %>%
    summarise(count = sum(quantity), lat = mean(start_lat), long = mean(start_long)) %>%
    ungroup()
  
  pres_obs <- obs[which(obs$count > 0),]
  
  ## Change to presence/absence and convert to vector
  obs <- pres_obs
  obs$count[which(obs$count > 0)] <- 1
  obs <- dplyr::select(obs, count, long, lat)
  obs <- vect(obs, geom = c("long", "lat"), crs="+proj=longlat +datum=WGS84")
  obs <- project(obs, crs(grid))
  
  png(file = paste0("species_maps/", gsub(" ", "_", spec), ".png"), width = 800, height = 800)
  plot(grid)
  plot(obs, add = TRUE)
  dev.off()

}
```


